#!/usr/bin/env bash
# audit-loc measures the source you have to read to trust tomo: the
# security-critical packages, counted in real lines. It backs the claim in
# AUDITING.md with a number CI keeps honest, so "here is the whole audit
# surface" stays true as the code moves.
#
#   scripts/audit-loc.sh           print the table
#   scripts/audit-loc.sh --write   rewrite the table block in AUDITING.md
#   scripts/audit-loc.sh --check   fail if AUDITING.md is stale or over budget
#
# Lines counted are non-test Go source, comments included: a reviewer reads the
# comments too, so counting them is the honest measure. The budget is a ceiling
# on the security-critical total, not on the whole tree.
set -euo pipefail

cd "$(dirname "$0")/.."

# The packages a reviewer should read first, each with what it enforces.
PACKAGES=(
  "pkg/policy|the fail-closed gate: allow/ask/deny, taint escalation, audit log"
  "pkg/sandbox|OS-level confinement of an approved exec-class command"
  "pkg/skill|the skills scanner and manifest parser for runtime SKILL.md files"
  "pkg/channel|the router, the driver registry, and per-channel allow-list wiring"
  "pkg/tool|the tool registry and capability classes the gate reasons over"
)

# BUDGET caps the security-critical total. Raise it deliberately in a PR when
# the surface genuinely grows, so the number is a decision, not a drift.
BUDGET=2600

count_pkg() {
  # Non-test .go files at the top of the package directory only.
  local dir="$1"
  find "$dir" -maxdepth 1 -name '*.go' ! -name '*_test.go' -print0 \
    | xargs -0 cat 2>/dev/null | wc -l | tr -d ' '
}

render_table() {
  local total=0
  printf '| package | lines | enforces |\n'
  printf '| --- | --- | --- |\n'
  for entry in "${PACKAGES[@]}"; do
    local dir="${entry%%|*}"
    local desc="${entry#*|}"
    local n
    n=$(count_pkg "$dir")
    total=$((total + n))
    printf '| `%s` | %s | %s |\n' "$dir" "$n" "$desc"
  done
  printf '| **total** | **%s** | audit budget: %s |\n' "$total" "$BUDGET"
  echo "$total" >/tmp/audit-loc-total
}

DOC="AUDITING.md"
BEGIN="<!-- BEGIN loc-table (generated by scripts/audit-loc.sh) -->"
END="<!-- END loc-table -->"

# extract_table prints the current table block from the doc, markers excluded.
extract_table() {
  awk -v begin="$BEGIN" -v end="$END" '
    $0 == end { grab=0 }
    grab { print }
    $0 == begin { grab=1 }
  ' "$DOC"
}

case "${1:-}" in
  --write)
    tmp=$(mktemp)
    render_table >"$tmp"
    awk -v begin="$BEGIN" -v end="$END" -v file="$tmp" '
      $0 == begin { print; while ((getline line < file) > 0) print line; skip=1; next }
      $0 == end { skip=0 }
      !skip { print }
    ' "$DOC" >"$DOC.tmp" && mv "$DOC.tmp" "$DOC"
    rm -f "$tmp"
    echo "updated $DOC"
    ;;
  --check)
    render_table >/dev/null
    total=$(cat /tmp/audit-loc-total)
    if [ "$total" -gt "$BUDGET" ]; then
      echo "audit surface is $total lines, over the $BUDGET budget."
      echo "shrink it, or raise BUDGET in scripts/audit-loc.sh in this PR."
      exit 1
    fi
    if [ "$(render_table)" != "$(extract_table)" ]; then
      echo "$DOC is out of date. Run: scripts/audit-loc.sh --write"
      exit 1
    fi
    echo "audit surface: $total lines, within the $BUDGET budget, and $DOC is current."
    ;;
  *)
    render_table
    ;;
esac
